# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
Install-PackageProvider nuget -Scope CurrentUser -Force -Confirm:$false
write-host "nuget installed"
 
Install-Module -Name AZ -AllowClobber -Scope CurrentUser -Force -Confirm:$False -SkipPublisherCheck
write-host "az installed"
 
Install-Module -Name d365fo.integrations  -AllowClobber -Scope CurrentUser -Force -Confirm:$false
write-host "d365fo.integrations installed"
 
Add-D365ODataConfig -Name "D365EnableUsers" -Tenant "AzureTenantId" -url "https://yourenvironment.sandbox.operations.dynamics.com" -ClientId "AzureApplicationId" -ClientSecret "AzureApplicationClientSecret"
write-host "Config added"
 
Set-D365ActiveODataConfig -Name D365EnableUsers
write-host "Config as default"

$token = Get-D365ODataToken
write-host "Token generated"

$SystemUsers = Get-D365ODataEntityData -EntityName SystemUsers -ODataQuery '$filter=Enabled eq false' -Token $token
#select the disabled users

$payload = '{"Enabled": "true"}'
#set the field names and the desired values to update

foreach ($user in $SystemUsers)
{
    #iterate through the users and create the [key, payload] array
    $userId = $user.UserID
    if($SystemUsersToUpdateNew)
    {
        $SystemUsersToUpdateNew += [PSCustomObject]@{Key = "UserID='$userId'"; Payload = $payload}
    }
    else {
        $SystemUsersToUpdateNew  = @([PSCustomObject]@{Key = "UserID='$userId'"; Payload = $payload})        
    }
}

Update-D365ODataEntityBatchMode -EntityName "SystemUsers" -Payload $SystemUsersToUpdateNew -Verbose -Token $token
#call the update command 
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"